### ISSUE TITLE
the structure of the whole project and the process to the breast dataset

### ISSUE THREAD

**Issue by Jww1063250817** [KarryRen/UML#1]
thanks a lot for your good job! and i want to know could you please show us  the structure of the whole project in a tree and your process to the breast dataset? thank you again!

**Comment by KarryRen** [comment]
Thank you for your attention! We are continuing to sort out the code and will follow up with a more clearly structured code that will be made public.

**Comment by KarryRen** [comment]
we have adjusted the code ~
