### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by xinruzhi** [KarryRen/UML#4]

**Comment by xinruzhi** [comment]
Hi author, I was trying to follow your configuration for the ISPY dataset training process, I found that the cls loss has been increasing and could not converge, tried to adjust the learning rate, still no effect
![Snipaste_2024-07-19_15-23-51](https://github.com/user-attachments/assets/7d814a8e-8c99-49c5-9031-cb22c17697c2)

**Comment by KarryRen** [comment]
I'm sorry, I haven't come across anything like this before. 
Speaking from experience, this could be due to issues with data preprocessing and spliting, and probably has little to do with the model and training process. I suggest you take a closer look at the preprocessing process of the dataset.

**Comment by xinruzhi** [comment]
> I'm sorry, I haven't come across anything like this before. Speaking from experience, this could be due to issues with data preprocessing and spliting, and probably has little to do with the model and training process. I suggest you take a closer look at the preprocessing process of the dataset.

Thank you for your reply and answer!

**Comment by xinruzhi** [comment]
In  `**ispy_dataset.py**`
The following changes were made
```
cls_label = np.array([int(image_name.split("_")[2])])  # shape=(1,) --->>
cls_label = int(image_name.split("_")[2])  # shape=(1,)
```
This problem has been solved.
Thanks to the author for the answer.
